version: "3"

services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - type: bind
        source: ./data
        target: /data/db
